services:
  _defaults:
    autowire: false

  App\Modules\Shared\Application\CommandBus:
    class: App\Modules\Shared\Application\CommandBus
    arguments:
      - App\Modules\User\Application\Create\UserCreatorCommand: '@App\Modules\User\Application\Create\UserCreatorCommandHandler'

