imports:
    - { resource: './command_bus.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Modules\User\:
    resource: '../src'


  App\Modules\Shared\Infrastructure\DoctrineDatabaseAdapter: ~

  App\Modules\Shared\Infrastructure\DatabaseAdapterInterface: '@App\Modules\Shared\Infrastructure\DoctrineDatabaseAdapter'