services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Modules\Shared\Domain\Entity\DoctrineDatabaseAdapter: ~

  App\Modules\Shared\Domain\Entity\DatabaseAdapterInterface: '@App\Modules\Shared\Domain\Entity\DoctrineDatabaseAdapter'