services:
  _defaults:
    autowire: false
    autoconfigure: false

  App\Modules\Shared\Application\CommandBus:
    class: App\Modules\Shared\Application\CommandBus
    arguments:
      - App\Modules\Inventory\Application\Create\CreateInventoryCommand: '@App\Modules\Inventory\Application\Create\CreateInventoryCommandHandler'

